### ISSUE TITLE
prepare_expert_data missing

### ISSUE THREAD

**Issue by Haichao-Zhang** [robfiras/ls-iq#1]
It seems that some codes are missing. E.g.  ``prepare_expert_data``:

Traceback (most recent call last):
  File "./lsiq_experiments.py", line 18, in <module>
    from imitation_lib.utils import prepare_expert_data, BestAgentSaver
ImportError: cannot import name 'prepare_expert_data' from 'imitation_lib.utils'

**Comment by robfiras** [comment]
Hi!
Thanks for your interest in this repo and sorry for the late reply. I was on travel and couldn't resolve this issue earlier.
Apparently, something went wrong while cleaning up the code. I fixed this issue now.
